package se.haleby.rps.port.http;

import io.javalin.Javalin;
import se.haleby.rps.application.GameApplicationService;
import se.haleby.rps.domain.model.Move;

import java.util.concurrent.CompletableFuture;

import static java.util.Objects.requireNonNull;

public class GameApi {

    private final Javalin app;
    private final int port;

    public GameApi(int port, GameApplicationService gameApplicationService) {
        this.port = port;
        app = Javalin.create();
        app.contextPath("/api/games/")
                .defaultContentType("text/plain")
                .enableAutogeneratedEtags()
                .disableStartupBanner()
                .enableCaseSensitiveUrls();

        // API
        app.put("/:gameId", ctx -> {
            String gameId = requireNonNull(ctx.pathParam("gameId"));
            String user = requireNonNull(ctx.header("user"));
            String move = ctx.formParam("move");

            final CompletableFuture<String> future;
            if (move == null) {
                future = gameApplicationService.startGame(gameId, user).thenApply(__ -> "Game started");
            } else {
                future = gameApplicationService.makeMove(gameId, user, Move.valueOf(move.toUpperCase())).thenApply(__ -> "Move made");
            }
            ctx.result(future);
        });
    }

    public void start() {
        app.start(port);
    }

    public void stop() {
        app.stop();
    }
}